---
# Action Repo: https://github.com/actions/starter-workflows

name: Greetings

# yamllint disable-line rule:truthy
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Thank you for creating your first Issue in this repository.
            We will review it and get back to you shortly.
          pr-message: >
            Thank you for submitting your first Pull Request to this repository.
            We will review it and get back to you shortly.
